# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EthereumSignerApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Web3Swift
  pod 'web3swift', git: 'https://github.com/BANKEX/web3swift.git'

  target 'EthereumSignerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
